### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by arkaitzmugica** [puentesarrin/bonzo#3]
I've followed your installation instructions, but...

> > > > import bonzo.smtp
> > > > Traceback (most recent call last):
> > > >   File "<stdin>", line 1, in <module>
> > > > ImportError: No module named bonzo.smtp

I'm using virtualenv. First I tried to install using pip, with pypy, and then I tried with in a "normal" python only enabled virtualenv. None of this methods worked for me.

**Comment by puentesarrin** [comment]
Hey,

Thanks for reaching out. The README file in master branch have an up-to-date version for a "Hello, World" example with Bonzo and have considered the new `bonzo.smtp` module. [This module is really new](http://bonzo.readthedocs.org/en/latest/releases/next.html#new-modules) and it's not part of the current release pushed to pypi. So if you want to test the latest code, please install Bonzo from its git repo by issuing:

```
$ pip install git+https://github.com/puentesarrin/bonzo.git
```

Please let me know if you have further questions!
